<?xml version="1.0" encoding="utf-8"?><messages><msg code="0" type="2">Start Time: Monday, July 17, 2023 9:03:42 AM</msg><msg code="0" type="0">Importing modules for the tool</msg><msg code="0" type="0">Getting excel data</msg><msg code="0" type="0">Checking the Excel data for errors</msg><msg code="0" type="0">0 records removed from the Excel data. See error file.</msg><msg code="0" type="0">Checking for updates and adds to GIS layer</msg><msg code="0" type="0">Processing updates...</msg><msg code="0" type="0">Applying updates against GIS data</msg><msg code="0" type="0">32 records updated in GIS layer</msg><msg code="0" type="0">Processing new additions...</msg><msg code="0" type="0">0 errors found in First Division check</msg><msg code="0" type="0">0 errors found in Second Division check</msg><msg code="0" type="0">2 records with audit data to review in Second Division check</msg><msg code="0" type="0">Getting PLSS features for the additional records</msg><msg code="0" type="0">180 to check for PLSS</msg><msg code="1" type="100">No PLSS records found for query: FRSTDIVID = 'CO060050N0670W0SN180' AND SECDIVNO = 'NWNW' Transaction number: OG-108320</msg><msg code="1" type="100">No PLSS records found for query: FRSTDIVID = 'CO060050N0670W0SN180' AND SECDIVNO = 'NWNW' Transaction number: OG-108320</msg><msg code="0" type="0">2 errors occured in the PLSS lookup</msg><msg code="0" type="0">Performing dissolve of PLSS features using Transaction Number field</msg><msg code="0" type="0">Consolidating the attribute data from new records to get total acres</msg><msg code="0" type="0">Merging data into gis layer</msg><msg code="1" type="100">Traceback (most recent call last):
  File "&lt;string&gt;", line 78, in execute
  File "C:\Users\logans1\Legal_Description_to_Feature\LD_Toolbox\legal_description_to_feature_v2.py", line 726, in main
    insert_new_data(gis_layer, dissolve_fc, data_to_insert)
  File "C:\Users\logans1\Legal_Description_to_Feature\LD_Toolbox\legal_description_to_feature_v2.py", line 188, in insert_new_data
    insert_cursor.insertRow(insert_row)
RuntimeError: Cannot find field 'Transactio'
</msg><msg code="-2147467259" type="100">Failed to execute (LegalDescriptionToFeature).</msg><msg code="0" type="3">Failed at Monday, July 17, 2023 9:07:51 AM (Elapsed Time: 4 minutes 9 seconds)</msg></messages>